### ISSUE TITLE
Formatting doesn't work with newly released Prettier v2.1.0

### ISSUE THREAD

**Issue by mhatvan** [sveltejs/prettier-plugin-svelte#123]
With Prettier v2.1.0, VSCode stops formatting `.svelte` files and the Svelte VSCode extension runs into `Error: unknown node type: undefined` pointing to `prettier-plugin-svelte` in the stacktrace as culprit.

**Comment by solidstatejake** [comment]
I've spent the last 5 hours trying to figure out what in God's name is preventing me from formatting my files. I have one vs code project open from yesterday which is still formatting perfectly. I diffed all relevant files in the new project with the old one and only found that the version of Prettier had been updated. Even after changing that, I still can't get it to work. Any idea what the problem is?

**Comment by michaelwooley** [comment]
For context, this [gist](https://gist.github.com/michaelwooley/9a3264884964fefbd0e0cb6ab11f1da8) contains my:

1. full error from VS Code svelte output
1. System info
1. VS Code extensions

**Comment by jasonlyu123** [comment]
https://github.com/sveltejs/prettier-plugin-svelte/blob/05bf9cb1b0d2224f9345f4dbba489bae18d6b24f/src/print/helpers.ts#L18
The problem seems to be this line. It uses it to check if the AST node is the root level. but for some reason, the new prettier version removes the 'tokens' property. The current workaround is to locate your prettier-plugin-svelte in `node_modules`. find the `isASTNode` function and remove `&& 'tokens' in n`.

**Comment by x4080** [comment]
@dummdidumm Its solved now ?

**Comment by michaelwooley** [comment]
Working for me. Thanks!

**Comment by x4080** [comment]
@michaelwooley cool

**Comment by michaelwooley** [comment]
@x4080 sorry should have elaborated a bit more on the sense in which this is working for me.

If I use versions:

- prettier 2.1.0
- prettier-plugin-svelte 1.1.1

Then the following command works fine:

```
prettier --write --plugin-search-dir=. ./**/*.svelte
```

_On VS Code_ there is a solution but just upgrading doesn't work. The language server is using local versions of the packages. It also assumes a dependency of 2.0.5 for prettier. So within your project try:

```
npm i prettier@2.0.5            # Pin to "older" version of prettier
npm i prettier-plugin-svelte  # Go ahead and upgrade plugin
```

I haven't checked to see if having v1.1.1 of the plugin is critical to making it work but it doesn't hurt.

Finally, restart VS Code, etc. to make sure that everything starts afresh.

Hope that helps?

**Comment by x4080** [comment]
@michaelwooley Thanks for reply, I just use svelte extension - so we need to use npm to make it work then, didnt know that. I'll try it later

**Comment by jasonlyu123** [comment]
We didn't update the prettier version of svelte-language-server so the bundled one should be `2.0.5`. But if there's workspace install we would use it.

**Comment by dummdidumm** [comment]
I just deployed an update of the VSCode extension which contains the v1.1.1 of `prettier-plugin-svelte`. It leaves Prettier at `2.0.5` to wait for some more bug fixes, but if you have a different Prettier version in your workspace then that one is used instead.

To get formatting again, you also have to update your `prettier-plugin-svelte` version in you workspace, which you have installed if you installed `svelte-check`. Simply update `svelte-check` for that. If you did not install `svelte-check` or `prettier-plugin-svelte` directly, you can skip this.

**Comment by x4080** [comment]
@michaelwooley and @dummdidumm 

I seems cant make it work, here's what I did :
1. If you use the VSCode extension, make sure you have version 101.11.0 or higher installed (CHECKED)
2. Delete your node_modules where your npm/yarn installs live (CHECKED)
3. Update your package.json: If you have svelte-check / prettier-plugin-svelte / svelte-language-server in there, set them to the latest version (I dont have any of those plugins installed), so I install them below 
4. npm i (to install all my deleted packages)
5. npm i prettier@2.0.5
6. npm i prettier-plugin-svelte
7. Change my settings.json to
```
{
  "[svelte]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "svelte.svelte-vscode"
  }
}

```

restart the vscode, open file .svelte, format document and no formatter found

This become like rocket science :)

**Comment by x4080** [comment]
@michaelwooley This command work though : (must add npx)
npx prettier --write --plugin-search-dir=. ./**/*.svelte

**Comment by michaelwooley** [comment]
@x4080 could you create a gist with: 

1. output from the language server
1. additional VS Code configuration
1. A package-lock.json (or yarn.lock) in your project folder

**Comment by x4080** [comment]
@michaelwooley Thanks for helping me, how to get output from the language server ? Maybe this is why my setting not working ?

**Comment by solidstatejake** [comment]
### Formatting in my editor works with the following setup:
- The VS Code Prettier extension is installed.
- The VS Code Svelte extension is installed and is the default formatter for .svelte files.
- Svelte formatting is enabled.
- The following packages were installed via npm:
  - svelte-check
  - prettier@2.0.5
  - prettier-plugin-svelte
- I reloaded VS Code.

That's what it took for formatting to work again (though, the only thing I changed was the prettier version, one might have settings different from mine that are affecting VS Code).

**Comment by x4080** [comment]
@michaelwooley Solve it ! It seems that my vs code is not updating, it said that cannot format if version is lower than xxxx, I force it to update and now it works

But before that, I installed svelte-check like @solidstatejake mentioned above

Thanks for all guys

**Comment by marcelocra** [comment]
> ### Formatting in my editor works with the following setup:
> * The VS Code Prettier extension is installed.
> * The VS Code Svelte extension is installed and is the default formatter for .svelte files.
> * Svelte formatting is enabled.
> * The following packages were installed via npm:
>   
>   * svelte-check
>   * prettier@2.0.5
>   * prettier-plugin-svelte
> * I reloaded VS Code.
> 
> That's what it took for formatting to work again (though, the only thing I changed was the prettier version, one might have settings different from mine that are affecting VS Code).

My setup was somewhat like that (I didn't check prettier version) and all I had to do was to reload the window (ctrl+shift+p, then type "Reload Window") and VSCode started formatting svelte files again.

Thanks!

**Comment by JPcorona14** [comment]
I was having this same issue and found if I removed the .prettierrc file, then it started working as normal.

**Comment by Foorack** [comment]
> I was having this same issue and found if I removed the .prettierrc file, then it started working as normal.
> 
> Edit: I commented out "plugins": ["prettier-plugin-svelte"] from the .prettierrc file and saved and the formatting seems to work with just that. Hope this helps!

Thank you! <3 This fixed it for me. Remove `prettier-plugin-svelte` from `.prettierrc` fixes formatting in Svelte files.

**Comment by BigAB** [comment]
I had this in the output from `svelte` (language server I presume) in the output tab when I hit save to format a svelte file.

```sh
Error: Cannot find module 'prettier-plugin-svelte'
Require stack:
- /Users/me/sveltekit-app/node_modules/prettier/index.js
- /Users/me/.vscode/extensions/svelte.svelte-vscode-106.4.1/node_modules/svelte-language-server/dist/src/importPackage.js
- /Users/me/.vscode/extensions/svelte.svelte-vscode-106.4.1/node_modules/svelte-language-server/dist/src/lib/documents/configLoader.js
- /Users/me/.vscode/extensions/svelte.svelte-vscode-106.4.1/node_modules/svelte-language-server/dist/src/lib/documents/Document.js
- /Users/me/.vscode/extensions/svelte.svelte-vscode-106.4.1/node_modules/svelte-language-server/dist/src/lib/documents/index.js
- /Users/me/.vscode/extensions/svelte.svelte-vscode-106.4.1/node_modules/svelte-language-server/dist/src/server.js
- /Users/me/.vscode/extensions/svelte.svelte-vscode-106.4.1/node_modules/svelte-language-server/bin/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at resolve (node:internal/modules/cjs/helpers:108:19)
    at /Users/me/sveltekit-app/node_modules/prettier/index.js:51552:21
    at Array.map (<anonymous>)
    at Object.load (/Users/me/sveltekit-app/node_modules/prettier/index.js:51544:61)
    at Object.load [as loadPlugins] (/Users/me/sveltekit-app/node_modules/prettier/index.js:16864:26)
    at /Users/me/sveltekit-app/node_modules/prettier/index.js:51618:28
    at Object.format (/Users/me/sveltekit-app/node_modules/prettier/index.js:51640:12)
    at SveltePlugin.formatDocument (/Users/me/.vscode/extensions/svelte.svelte-vscode-106.4.1/node_modules/svelte-language-server/dist/src/plugins/svelte/SveltePlugin.js:66:40)
    at async PluginHost.tryExecutePlugin (/Users/me/.vscode/extensions/svelte.svelte-vscode-106.4.1/node_modules/svelte-language-server/dist/src/plugins/PluginHost.js:321:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/me/sveltekit-app/node_modules/prettier/index.js',
    '/Users/me/.vscode/extensions/svelte.svelte-vscode-106.4.1/node_modules/svelte-language-server/dist/src/importPackage.js',
    '/Users/me/.vscode/extensions/svelte.svelte-vscode-106.4.1/node_modules/svelte-language-server/dist/src/lib/documents/configLoader.js',
    '/Users/me/.vscode/extensions/svelte.svelte-vscode-106.4.1/node_modules/svelte-language-server/dist/src/lib/documents/Document.js',
    '/Users/me/.vscode/extensions/svelte.svelte-vscode-106.4.1/node_modules/svelte-language-server/dist/src/lib/documents/index.js',
    '/Users/me/.vscode/extensions/svelte.svelte-vscode-106.4.1/node_modules/svelte-language-server/dist/src/server.js',
    '/Users/me/.vscode/extensions/svelte.svelte-vscode-106.4.1/node_modules/svelte-language-server/bin/server.js'
  ]
}
```

Maybe that can help figure out the problem?

For now 
> Edit: I commented out "plugins": ["prettier-plugin-svelte"] from the .prettierrc file and saved and the formatting seems to work with just that. Hope this helps!

Works for me, so I'll go with that, but it seems not the right solution, as CI and such probably need that when running formatting.
