### ISSUE TITLE
Incompatible with `stylelint-prettier`

### ISSUE THREAD

**Issue by JounQin** [sveltejs/prettier-plugin-svelte#210]
```svelte
<!-- test.svelte -->
<style>
  .test {
    border: transparent;
  }
</style>
```

```jsonc
// .stylelintrc
{
  "plugins": [
    "stylelint-prettier"
  ],
  "rules": {
    "prettier/prettier": true
  }
}
```

command `stylelint test.svelte` fails with:

```log
$ /Users/JounQin/Workspaces/Local/test/node_modules/.bin/stylelint test.svelte
ParseError: Expected }
  1 | .test {
> 2 |     border: transparent;
    |          ^
  3 |   }
    at error (/Users/JounQin/Workspaces/Local/test/node_modules/svelte/compiler.js:16748:20)
    at Parser$1.error (/Users/JounQin/Workspaces/Local/test/node_modules/svelte/compiler.js:16824:10)
    at Parser$1.eat (/Users/JounQin/Workspaces/Local/test/node_modules/svelte/compiler.js:16838:19)
    at mustache (/Users/JounQin/Workspaces/Local/test/node_modules/svelte/compiler.js:16641:17)
    at new Parser$1 (/Users/JounQin/Workspaces/Local/test/node_modules/svelte/compiler.js:16783:22)
    at Object.parse$3 [as parse] (/Users/JounQin/Workspaces/Local/test/node_modules/svelte/compiler.js:16915:21)
    at Object.parse (/Users/JounQin/Workspaces/Local/test/node_modules/prettier-plugin-svelte/plugin.js:1672:83)
    at Object.parse (/Users/JounQin/Workspaces/Local/test/node_modules/prettier/index.js:13625:19)
    at coreFormat (/Users/JounQin/Workspaces/Local/test/node_modules/prettier/index.js:14899:14)
    at format (/Users/JounQin/Workspaces/Local/test/node_modules/prettier/index.js:15131:14)
```

**Comment by dummdidumm** [comment]
I'm not sure how to proceed here. The problem is that `stylelint` extracts the CSS part from the Svelte file, which in turn is then handed to `prettier-plugin-svelte`. So in your example the plugin gets

```svelte
  .test {
    border: transparent;
  }
```

Which is obviously invalid Svelte code. To me this sounds like you need to somehow tell Prettier to route this code to its CSS formatter and not to the Svelte plugin.

**Comment by JounQin** [comment]
Hmm, `.html` and `.vue` files are similar but works fine, maybe prettier handles html and vue specially?

**Comment by dummdidumm** [comment]
Vue and HTML support are built-in to prettier core. Maybe their source code can reveal how they deal with that in this situation.

**Comment by JounQin** [comment]
It seems to be related to https://github.com/prettier/stylelint-prettier/blob/master/stylelint-prettier.js#L90-L97, I'll raise a PR there instead.

Thanks for your help.
