### ISSUE TITLE
Plugin fails to format files with style: directive

### ISSUE THREAD

**Issue by YevhenKap** [sveltejs/prettier-plugin-svelte#293]
When a Svelte file contains something like the next code:

```html
<div style:top="{0}" />
```

Prettier plugin fails with the next error:

```
["ERROR" - 10:22:52 PM] Error formatting document.
["ERROR" - 10:22:52 PM] unknown node type: StyleDirective
Error: unknown node type: StyleDirective
	at Object.print (/Users/blah/project/node_modules/prettier-plugin-svelte/plugin.js:1328:11)
	at callPluginPrintFunction (/Users/blah/project/node_modules/prettier/index.js:14259:21)
	at mainPrintInternal (/Users/blah/project/node_modules/prettier/index.js:14197:17)
	at mainPrint (/Users/blah/project/node_modules/prettier/index.js:14179:14)
	at AstPath$1.call (/Users/blah/project/node_modules/prettier/index.js:13918:20)
```

**Comment by YevhenKap** [comment]
Sorry, I am using the old version of the plugin: `2.5.1`. The last `2.7.0` doesn't have that issue.
