### ISSUE TITLE
Looks broken for Prettier 3.0?

### ISSUE THREAD

**Issue by plitokpikin** [sveltejs/prettier-plugin-svelte#384]
Trying to format a ` .Svelte` file using the plugin, but I get:

```
["ERROR" - 9:47:20 PM] Error formatting document.
["ERROR" - 9:47:20 PM] printer.embed has too many parameters. The API changed in Prettier v3. Please update your plugin. See https://prettier.io/docs/en/plugins.html#optional-embed
Error: printer.embed has too many parameters. The API changed in Prettier v3. Please update your plugin. See https://prettier.io/docs/en/plugins.html#optional-embed
    at printEmbeddedLanguages (file:///C:/git/project/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:17963:11)
    at printAstToDoc (file:///C:/git/project/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:18094:9)
    at async coreFormat (file:///C:/git/project/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:18405:14)
    at async formatWithCursor (file:///C:/git/project/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:18603:14)
    at async Module.format2 (file:///C:/git/project/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:21789:25)
```

Package version is the latest one:
```json
"plugins": [
    "C:\\git\\project\\node_modules\\.pnpm\\prettier-plugin-svelte@2.10.1_prettier@3.0.0_svelte@4.0.5\\node_modules\\prettier-plugin-svelte\\plugin.js"
  ]
```

**Comment by Conduitry** [comment]
It's not supported yet. #317.
